server:
    port: 18082
    server-header: unitforum

spring:
    mvc:
        view:
            prefix: /WEB-INF/jsp/
            suffix: .jsp
            staticPathPattern: /**
    resources:
        staticLocations: file:./src/main/webapp/WEB-INF/static

logging:
    config: file:./config/logback.xml

# DB
datasource:
    unitforum:
        driverClassName: "com.mysql.jdbc.Driver"
        url: "jdbc:mysql://{mysql_host}:{mysql_port}/unitforumdb?autoReconnect=true&initialTimeout=3&maxReconnects=5&useUnicode=true&characterEncoding=utf8"
        username: {mysql_id}
        password: {mysql_password}
        testOnBorrow: true
        testWhileIdle: true
        validationQuery: SELECT 1 

application:
    environment: Dev
    localeParam: lang
    articleRowCount: 10
    staticResource: /static
    messageResource: classpath:/messages/message
